server:
  port: 12345
spring:
  application:
    name: station-center
  datasource:
    username: yourUserName
    password: "password"
    url: jdbc:mysql://localhost:3306/mission_center?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml
#logging:
#  level:
#    cn.zora.cloud.repository: debug